rm(list=ls())
suppressMessages(library(glmnet))
suppressMessages(library(reticulate))
load('glmnet_grouped.RData')

use_condaenv('BayesRetro')
# py_config()
np <- import('numpy', convert=T)
sp <- import('scipy.sparse', convert=T)

args <- commandArgs(trailingOnly=TRUE)
reaction_num <- as.integer(args[1])
cand_step1_fps_path <- paste0('reaction', reaction_num, '_step1.npz')
cand_step1_fps <- sp$load_npz(cand_step1_fps_path)
cand_prob  <- predict(fit_grouped, newx=cand_step1_fps, type="response", s=best_lambda)
output_path  <- paste0('reaction', reaction_num, '_step1_prob.csv')
write.csv(cand_prob, file=output_path, row.names=F)
cand_step2_fps_path <- paste0('reaction', reaction_num, '_step2.npz')
cand_step2_fps <- sp$load_npz(cand_step2_fps_path)
cand_prob  <- predict(fit_grouped, newx=cand_step2_fps, type="response", s=best_lambda)
output_path  <- paste0('reaction', reaction_num, '_step2_prob.csv')
write.csv(cand_prob, file=output_path, row.names=F)
